name: Feature Request
description: Suggest a new feature for this project
title: "feat: "
labels: ["feat"]
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: What feature would you like to see?
      placeholder: Describe the feature and why it's needed
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: What needs to be done?
      placeholder: |
        -
        -
    validations:
      required: true